[package]
name = "client"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"

[dependencies]
client-app.path = "app"
common-macros.workspace = true
common-logger.workspace = true
leptos.workspace = true
leptos_animated_for.workspace = true
leptos_i18n.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
time.workspace = true
wasm-bindgen.workspace = true
getrandom = { workspace = true, optional = true }

[features]
csr = [
  "dep:getrandom",
  "time/wasm-bindgen",
  "leptos/csr",
  "leptos_i18n/csr",
  "leptos_meta/csr",
  "leptos_router/csr",
]
ssr = [
  "leptos/ssr",
  "leptos_animated_for/ssr",
  "leptos_meta/ssr",
  "leptos_router/ssr",
  "leptos_i18n/axum",
]

[package.metadata.cargo-all-features]
skip_feature_sets = [
  ["csr", "ssr"],
  ["_client-deps", "_server-deps"],
  ["client", "server"],
]
