[package]
name = "client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"

[dependencies]
common.workspace = true
cfg-if.workspace = true
client_app.path = "app"
leptos.workspace = true
wasm-bindgen.workspace = true

[build-dependencies]
common.workspace = true
client_macros.workspace = true
serde.workspace = true

[features]
vite-prebuild = []
pwa = ["client_app/pwa"]
csr = ["common/csr"]
hydrate = ["common/hydrate"]
ssr = ["common/ssr"]

[package.metadata.cargo-all-features]
skip_feature_sets = [["csr", "ssr"], ["hydrate", "ssr"], ["hydrate", "csr"]]
 