name: Setup

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cache

    - name: Just setup
      shell: bash
      run: cargo install just@1.15.0

    - name: Project CI setup
      shell: bash
      run: just setup-ci
