name: Setup

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/cache
    - uses: extractions/setup-just@v1

    - name: Project CI setup
      shell: bash
      run: just setup-ci
