name: Setup

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Cargo cache setup
      uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: true

    - name: pnpm setup
      uses: pnpm/action-setup@v2

    - name: Node setup
      uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: pnpm

    - name: Just setup
      shell: bash
      run: cargo install just@1.15.0

    - name: Project CI setup
      shell: bash
      run: just setup-ci
