name: Setup

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/cache

    - name: Just setup
      shell: bash
      run: sudo snap install --edge --classic just

    - name: Project CI setup
      shell: bash
      run: just setup-ci
