[workspace]
resolver = "2"
members = [
  "build/core",
  "build/pwa",
  "apps/client",
  "apps/client/app",
  "apps/client/components",
  "apps/client/composables",
  "apps/client/env",
  "apps/client/i18n",
  "apps/client/layouts",
  "apps/client/macros",
  "apps/client/macros/proc",
  "apps/client/pages/about",
  "apps/client/pages/hi/index",
  "apps/client/pages/hi/[name]",
  "apps/client/pages/home",
  "apps/client/pages/404",
  "apps/client/router",
  "apps/client/stores",
  "apps/client/utils",
  "apps/server",
  "packages/exports",
  "packages/logger",
  "packages/macros",
  "packages/macros/proc",
  "packages/utils",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
rust-version = "1.73"

[workspace.dependencies]
client.path = "apps/client"
client_components.path = "apps/client/components"
client_composables.path = "apps/client/composables"
client_env.path = "apps/client/env"
client_i18n.path = "apps/client/i18n"
client_macros.path = "apps/client/macros"
client_router.path = "apps/client/router"
client_stores.path = "apps/client/stores"
client_utils.path = "apps/client/utils"
exports.path = "packages/exports"
logger.path = "packages/logger"
macros.path = "packages/macros"
utils.path = "packages/utils"
server.path = "apps/server"
# full-stack
anyhow = "1.0.75"
cfg-if = "1.0.0"
derive-getters = "0.3.0"
derive_more = "0.99.17"
derive_setters = "0.1.6"
educe = "0.5.7"
futures = "0.3.29"
leptos = { version = "0.5.4", features = ["nightly"] }
leptos_animated_for = "0.1.0"
leptos_i18n = { version = "0.2.3", features = [
  "nightly",
  "serde",
  "cookie",
  "interpolate_display",
  "yaml_files",
], default-features = false }
leptos_meta = { version = "0.5.4", features = ["nightly"] }
leptos_router = { version = "0.5.4", features = ["nightly"] }
leptos-use = {version = "0.9.0", features = ["serde"]}
log = "0.4.20"
paste = "1.0.14"
pct-str = "2.0.0"
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.50"
time = { version = "0.3.30", features = ["macros", "formatting", "parsing"] }
unocss-classes = "2.0.0"
wasm-bindgen = "0.2.89"
web-sys = { version = "0.3.66", features = [
  "CssStyleDeclaration",
  "DomRect",
  "DomTokenList",
  "Element",
  "Event",
  "EventTarget",
  "HtmlElement",
  "MediaQueryList",
  "Performance",
] }
# client_only
getrandom = { version = "0.2.11", features = ["js"] }
# server-only
axum = "0.6.20"
leptos_axum = "0.5.4"
leptos_integration_utils = "0.5.4"
tokio = { version = "1.35.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.4.4", features = ["fs"] }
# proc macros
proc-macro2 = "1.0.70"
quote = "1.0.33"
syn = { version = "2.0.41", features = ["full"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.dev-ci]
inherits = "dev"
opt-level = 0

[profile.dev-ci.package."*"]
opt-level = 0

[profile.client-dev]
inherits = "dev"

[profile.server-dev]
inherits = "dev"

[profile.client-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[profile.server-release]
inherits = "release"

[[workspace.metadata.leptos]]
name = "core"
bin-package = "core"
lib-package = "client"
site-root = "target/client"
site-pkg-dir = "hydrate"
output-name = "app"
assets-dir = "target/client-prebuild"
site-addr = "127.0.0.1:3333"
reload-port = 3334
bin-features = []
bin-default-features = false
bin-profile-dev = "server-dev"
bin-profile-release = "server-release"
lib-features = ["hydrate", "vite-prebuild"]
lib-default-features = false
lib-profile-dev = "client-dev"
lib-profile-release = "client-release"

[[workspace.metadata.leptos]]
name = "core-pwa"
bin-package = "pwa"
lib-package = "client"
site-root = "target/client-prebuild/pwa"
site-pkg-dir = ""
output-name = "app"
bin-features = []
bin-default-features = false
bin-profile-dev = "server-dev"
bin-profile-release = "server-release"
lib-features = ["csr", "pwa"]
lib-default-features = false
lib-profile-dev = "client-dev"
lib-profile-release = "client-release"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
# warn
pedantic = { level = "warn", priority = -1 }
clone_on_ref_ptr = "warn"
disallowed_macros = "warn"
disallowed_methods = "warn"
disallowed_types = "warn"
dbg_macro = "warn"
deref_by_slicing = "warn"
empty_structs_with_brackets = "warn"
float_cmp_const = "warn"
fn_to_numeric_cast_any = "warn"
get_unwrap = "warn"
integer_division = "warn"
implied_bounds_in_impls = "warn"
lossy_float_literal = "warn"
map_err_ignore = "warn"
multiple_inherent_impl = "warn"
mutex_atomic = "warn"
panic_in_result_fn = "warn"
partial_pub_fields = "warn"
print_stderr = "warn"
print_stdout = "warn"
pub_without_shorthand = "warn"
rc_mutex = "warn"
ref_patterns = "warn"
redundant_clone = "warn"
redundant_type_annotations = "warn"
rest_pat_in_fully_bound_structs = "warn"
self_named_module_files = "warn"
semicolon_inside_block = "warn"
str_to_string = "warn"
string_to_string = "warn"
suspicious_xor_used_as_pow = "warn"
todo = "warn"
try_err = "warn"
unimplemented = "warn"
unnecessary_self_imports = "warn"
unneeded_field_pattern = "warn"
unreachable = "warn"
unseparated_literal_suffix = "warn"
use_debug = "warn"
verbose_file_reads = "warn"
# allow
cast_precision_loss = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"
return_self_not_must_use = "allow"
