[package]
name = "client_layouts"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
client_components.workspace = true
client_composables.workspace = true
client_env.workspace = true
client_i18n.workspace = true
client_router.workspace = true
common.workspace = true
server.workspace = true
leptos.workspace = true
leptos_i18n.workspace = true
leptos_router.workspace = true
leptos-use.workspace = true
unocss-classes.workspace = true
