[package]
name = "client-layouts"
version.workspace = true
edition.workspace = true
publish = false

[lib]
path = "lib.rs"

[dependencies]
client-components.workspace = true
client-composables.workspace = true
client-env.workspace = true
client-globals.workspace = true
client-macros.workspace = true
client-router.workspace = true
leptos.workspace = true
leptos_i18n.workspace = true
leptos_router.workspace = true
leptos-use.workspace = true
unocss-classes.workspace = true
