[package]
name = "client-page-home"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
client-components.workspace = true
client-composables.workspace = true
client-env.workspace = true
client-globals.workspace = true
client-i18n.workspace = true
client-router.workspace = true
client-stores.workspace = true
leptos.workspace = true
leptos_i18n.workspace = true
leptos_router.workspace = true
unocss-classes.workspace = true
web-sys.workspace = true
