[package]
name = "client_page-home"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
client_components.workspace = true
client_composables.workspace = true
client_env.workspace = true
client_i18n.workspace = true
client_router.workspace = true
client_stores.workspace = true
common = { workspace = true, features = ["leptos"] }
leptos.workspace = true
leptos_router.workspace = true
web-sys.workspace = true
