[package]
name = "common_utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
common_exports.workspace = true

[features]
client = []
server = []
