[package]
name = "exports"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
macros.workspace = true
derive-getters.workspace = true
derive_setters.workspace = true
educe.workspace = true
leptos.workspace = true
leptos_i18n = { workspace = true, optional = true }
serde.workspace = true
log.workspace = true
time.workspace = true
unocss-classes = { workspace = true, optional = true }

[features]
client = ["dep:leptos_i18n", "dep:unocss-classes"]
server = []
