[package]
name = "client-page-about"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
client-components.workspace = true
client-composables.workspace = true
client-globals.workspace = true
client-utils.workspace = true
leptos.workspace = true
leptos_i18n.workspace = true
rand.workspace = true
unocss-classes.workspace = true
