[package]
name = "client_components"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
client_composables.workspace = true
client_router.workspace = true
common = { workspace = true, features = ["leptos"] }
leptos.workspace = true
leptos_animated_for.workspace = true
wasm-bindgen.workspace = true
web-sys.workspace = true
