[package]
name = "client_components"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
client_hooks.workspace = true
client_macros.workspace = true
client_router.workspace = true
client_utils.workspace = true
common.workspace = true
leptos.workspace = true
leptos_animated_for = "0.4.4"
leptos_icons = "0.3.0"

[dev-dependencies]
dev.workspace = true
wasm-bindgen-test.workspace = true
