[package]
name = "client_components"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
client_hooks.workspace = true
client_router.workspace = true
common.workspace = true
leptos.workspace = true
leptos_animated_for.workspace = true
leptos_icons = "0.2.1"
wasm-bindgen.workspace = true
web-sys.workspace = true
