[package]
name = "client_composables"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
client_i18n.workspace = true
client_macros.workspace = true
client_utils.workspace = true
exports = { workspace = true, features = ["client"] }
utils.workspace = true
futures.workspace = true
leptos-use.workspace = true
log.workspace = true
paste.workspace = true
wasm-bindgen.workspace = true
web-sys.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = { version = "1.0.0", features = ["color"] }
fern = "0.6.2"
