[package]
name = "client-page-hi"
version.workspace = true
edition.workspace = true
publish = false

[lib]
path = "lib.rs"

[dependencies]
client-components.workspace = true
client-composables.workspace = true
client-globals.workspace = true
client-router.workspace = true
client-stores.workspace = true
leptos.workspace = true
leptos_i18n.workspace = true
leptos_router.workspace = true
pct-str.workspace = true
