[package]
name = "client-router"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
leptos.workspace = true
leptos_router.workspace = true
