[package]
name = "common"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
common_logger = { path = "logger", optional = true }
common_macros.path = "macros"
common_utils = { path = "utils", optional = true }
cfg-if.workspace = true
derive-getters.workspace = true
derive_setters.workspace = true
educe.workspace = true
serde.workspace = true
leptos = { workspace = true, optional = true }
leptos_i18n = { workspace = true, optional = true }
log.workspace = true
unocss-classes.workspace = true

[features]
leptos = ["dep:leptos", "dep:leptos_i18n"]
logger = ["dep:common_logger"]
utils = ["dep:common_utils"]
csr = ["common_logger/csr"]
ssr = ["common_logger/ssr"]

[package.metadata.cargo-all-features]
skip_feature_sets = [["csr", "ssr"]]
