[package]
name = "client_proc_macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
ahash = "0.8.7"
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lib]
path = "lib.rs"
proc-macro = true
