[package]
name = "client_proc_macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
common.workspace = true
proc-macro2.workspace = true
quote.workspace = true
regex = "1.10.3"
syn.workspace = true
wax = "0.6.0"

[lib]
path = "lib.rs"
proc-macro = true
