[env]
PROJECT_REPOSITORY_URL = "https://github.com/brofrain/leptos-assembly"

[build]
rustflags = ["-Z", "threads=8"]

[unstable]
codegen-backend = true

[profile.server-dev]
codegen-backend = "cranelift"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]

[target.wasm32-unknown-unknown]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]
