[package]
name = "dev"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
common.workspace = true
insta = "1.34.0"
leptos = { workspace = true, features = ["csr"] }
wasm-bindgen.workspace = true
