[package]
name = "dev"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
common.workspace = true
insta = { version = "1.34.0", features = ["yaml"] }
wasm-bindgen.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
leptos = { workspace = true, features = ["csr"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
leptos = { workspace = true, features = ["ssr"] }
