[package]
name = "server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
common.workspace = true
leptos.workspace = true
log.workspace = true
reqwest = { version = "0.11.23", features = ["json"] }
serde.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum.workspace = true
leptos_axum.workspace = true
leptos_integration_utils.workspace = true
tracing-subscriber.workspace = true
tower.workspace = true
tower-http.workspace = true
