[package]
name = "client_pages"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
client_components.workspace = true
client_hooks.workspace = true
client_env.workspace = true
client_i18n.workspace = true
client_router.workspace = true
client_stores.workspace = true
client_utils.workspace = true
exports = { workspace = true, features = ["client"] }
utils.workspace = true
leptos.workspace = true
leptos_router.workspace = true
pct-str.workspace = true
rand.workspace = true
web-sys.workspace = true
