[package]
name = "client_utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
exports = { workspace = true, features = ["client"] }
futures.workspace = true
