[package]
name = "client_utils"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
common = { workspace = true, features = ["leptos"] }
futures.workspace = true
