[package]
name = "common_logger"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
common_macros.path = "../macros"
cfg-if.workspace = true
console_log = { workspace = true, optional = true }
log.workspace = true
time = { workspace = true, optional = true }
fern = "0.6.2"
owo-colors = { version = "3.5.0", optional = true }

[features]
csr = ["dep:console_log"]
ssr = ["dep:owo-colors", "dep:time"]
