[package]
name = "client_app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
client_components.workspace = true
client_composables.workspace = true
client_env.workspace = true
client_i18n.workspace = true
client_layouts.path = "../layouts"
client_macros.workspace = true
client_pages.path = "../pages"
client_router.workspace = true
client_utils.workspace = true
exports = { workspace = true, features = ["client"] }
macros.workspace = true
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos-use.workspace = true
wasm-bindgen.workspace = true
web-sys.workspace = true

[features]
pwa = []
