[package]
name = "client_app"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
client_components.workspace = true
client_composables.workspace = true
client_env.workspace = true
client_i18n.workspace = true
client_layouts.path = "../layouts"
client_macros.workspace = true
client_page-about.path = "../pages/about"
client_page-hi.path = "../pages/hi"
client_page-home.path = "../pages/home"
client_page-404.path = "../pages/404"
client_router.workspace = true
client_utils.workspace = true
common = { workspace = true, features = ["leptos"] }
leptos.workspace = true
leptos_i18n.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos-use.workspace = true
unocss-classes.workspace = true

[features]
csr = []
ssr = []

[package.metadata.cargo-all-features]
skip_feature_sets = [["csr", "ssr"]]
