name: Review

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches: "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

  fmt:
    name: Formatting
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache
      - name: Formatting
        run: just fmt-check

  check:
    name: Check
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache
      - name: Check
        run: just check

  lint:
    name: Lint
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache
      - name: Lint
        run: just lint-ci

  build-tests:
    name: Build tests
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache
      - name: Build tests
        run: just build-tests

  test:
    name: Tests
    needs: build-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache
      - name: Tests
        run: just test

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache
      - name: Build
        run: just build

  e2e:
    name: E2E
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache
      - name: E2E
        run: just e2e

  audit:
    name: Dependency audit
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache
      - name: Outdated Cargo dependencies check (emit warning only)
        run: just outdated-rs || echo "::warning ::Some Cargo dependencies are autdated"
      - name: Outdated Node dependencies check (emit warning only)
        run: just outdated-js || echo "::warning ::Some Node dependencies are autdated"
      - name: Unused Cargo dependencies check (emit warning only)
        run: just ununsed || echo "::warning ::Some Rust dependencies are unused"
      - name: Security vulnerabilities audit
        run: just audit
