name: Review

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches: "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

  quality:
    name: Source code quality
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Formatting
        run: just fmt-check
      - name: Lint
        run: just lint
      - name: Tests
        run: just test
      - name: E2E
        run: just e2e-release

  audit:
    name: Dependency audit
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Outdated Cargo dependencies check (emit warning only)
        run: just outdated-cargo || echo "::warning ::Some Cargo dependencies are autdated"
      - name: Outdated Node dependencies check (emit warning only)
        run: just outdated-pnpm || echo "::warning ::Some Node dependencies are autdated"
      - name: Security vulnerabilities audit
        run: just audit
